# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStackedWidget
from qfluentwidgets import TitleLabel, NavigationBar, FluentIcon, NavigationInterface

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 创建NavigationBar
        self.navigationBar = NavigationBar(self.centralwidget)
        self.navigationBar.setGeometry(QtCore.QRect(0, 0, 80, 600))  # 设置位置和大小
        self.navigationBar.setObjectName("navigationBar")

        # 创建StackedWidget
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 0, 721, 591))
        self.stackedWidget.setObjectName("stackedWidget")

        # 添加页面
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.TitleLabel = TitleLabel(self.homepage)
        self.TitleLabel.setGeometry(QtCore.QRect(140, 40, 441, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.stackedWidget.addWidget(self.homepage)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)

        # 添加导航项并绑定页面
        self.navigationBar.addItem("首页", text="首页",icon=FluentIcon.HOME, onClick=lambda: self.stackedWidget.setCurrentIndex(0))
        self.navigationBar.addItem("赤石工具集",text="赤石", icon="star.svg", onClick=lambda: self.stackedWidget.setCurrentIndex(1))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "我们非常不欢迎您使用赤石工具箱"))

# 注意：你需要确保图标文件(home.png和settings.png)存在于你的项目目录中，或者提供正确的路径。

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
