# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'lemonhelper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 388)

        current_dir = os.path.dirname(os.path.abspath(__file__))
        icon_path = os.path.join(current_dir, "icon.png")
        MainWindow.setWindowIcon(QtGui.QIcon(icon_path))


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleLabel = TitleLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(10, 10, 261, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.Github = PushButton(self.centralwidget)
        self.Github.setGeometry(QtCore.QRect(410, 80, 151, 32))
        self.Github.setObjectName("Github")
        self.BodyLabel = BodyLabel(self.centralwidget)
        self.BodyLabel.setGeometry(QtCore.QRect(450, 40, 121, 19))
        self.BodyLabel.setObjectName("BodyLabel")
        self.BodyLabel_2 = BodyLabel(self.centralwidget)
        self.BodyLabel_2.setGeometry(QtCore.QRect(450, 60, 111, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.Color = ComboBox(self.centralwidget)
        self.Color.setGeometry(QtCore.QRect(10, 110, 101, 32))
        self.Color.setObjectName("Color")
        self.BodyLabel_3 = BodyLabel(self.centralwidget)
        self.BodyLabel_3.setGeometry(QtCore.QRect(10, 80, 111, 19))
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.Enable_music = CheckBox(self.centralwidget)
        self.Enable_music.setGeometry(QtCore.QRect(10, 150, 141, 22))
        self.Enable_music.setObjectName("Enable_music")
        self.Fonts = LineEdit(self.centralwidget)
        self.Fonts.setGeometry(QtCore.QRect(10, 260, 128, 33))
        self.Fonts.setObjectName("Fonts")
        self.BodyLabel_4 = BodyLabel(self.centralwidget)
        self.BodyLabel_4.setGeometry(QtCore.QRect(10, 220, 111, 19))
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.BodyLabel_5 = BodyLabel(self.centralwidget)
        self.BodyLabel_5.setGeometry(QtCore.QRect(10, 300, 121, 19))
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.Run = PushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(350, 230, 211, 151))
        self.Run.setObjectName("Run")
        self.BodyLabel_6 = BodyLabel(self.centralwidget)
        self.BodyLabel_6.setGeometry(QtCore.QRect(440, 200, 121, 19))
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.Font_dict = ComboBox(self.centralwidget)
        self.Font_dict.setGeometry(QtCore.QRect(10, 330, 101, 32))
        self.Font_dict.setObjectName("Font_dict")
        self.music = ComboBox(self.centralwidget)
        self.music.setGeometry(QtCore.QRect(10, 180, 101, 32))
        self.music.setObjectName("music")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Color.setObjectName("Color")
        self.Color.addItem("green", userData="green")
        self.Color.addItem("red", userData="red")
        self.Color.addItem("blue", userData="blue ")
        self.Color.addItem("yellow", userData="yellow")
        self.Color.addItem("white", userData="white")
        self.Color.addItem("cyan", userData="cyan")
        self.Color.addItem("magenta", userData="magenta")
        self.Color.addItem("black", userData="black")

        items =["a","A","c","C","e","g","G","k","m","n","o","p","P","r","R","s","S"]
        self.Font_dict.addItems(items)
        self.music.addItem(text="佳豪小曲",userData="jiahao")
        self.music.addItem(text="Faded",userData="faded")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "柠檬小助手"))
        self.TitleLabel.setText(_translate("MainWindow", "欢迎使用柠檬小助手"))
        self.Github.setText(_translate("MainWindow", "点我查看原项目主页"))
        self.BodyLabel.setText(_translate("MainWindow", "原项目UniMatrix"))
        self.BodyLabel_2.setText(_translate("MainWindow", "使用GPL3.0开源"))
        self.Color.setText(_translate("MainWindow", "请选择"))
        self.BodyLabel_3.setText(_translate("MainWindow", "代码雨颜色"))
        self.Enable_music.setText(_translate("MainWindow", "启用佳豪音乐？"))
        self.Fonts.setText(_translate("MainWindow", "请输入文本"))
        self.BodyLabel_4.setText(_translate("MainWindow", "代码雨字符"))
        self.BodyLabel_5.setText(_translate("MainWindow", "代码雨预设字符集"))
        self.Run.setText(_translate("MainWindow", "启动！"))
        self.BodyLabel_6.setText(_translate("MainWindow", "TIP 不配置也能用"))
        self.Font_dict.setText(_translate("MainWindow", "请选择"))
        self.music.setText(_translate("MainWindow", "音乐"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, LineEdit, PushButton, TitleLabel
