# Form implementation generated from reading ui file 'lemonhelper.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 387)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Color = ComboBox(parent=self.centralwidget)
        self.Color.setObjectName("Color")
        self.gridLayout.addWidget(self.Color, 3, 0, 2, 1)
        self.Font_dict = ComboBox(parent=self.centralwidget)
        self.Font_dict.setObjectName("Font_dict")
        self.gridLayout.addWidget(self.Font_dict, 11, 0, 1, 1)
        self.BodyLabel_2 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout.addWidget(self.BodyLabel_2, 1, 3, 1, 1)
        self.BodyLabel_7 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.gridLayout.addWidget(self.BodyLabel_7, 2, 1, 1, 2)
        self.BodyLabel = BodyLabel(parent=self.centralwidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 3, 1, 1)
        self.music = ComboBox(parent=self.centralwidget)
        self.music.setObjectName("music")
        self.gridLayout.addWidget(self.music, 6, 0, 1, 1)
        self.Run = PushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Run.sizePolicy().hasHeightForWidth())
        self.Run.setSizePolicy(sizePolicy)
        self.Run.setObjectName("Run")
        self.gridLayout.addWidget(self.Run, 8, 3, 4, 1)
        self.TitleLabel = TitleLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 3)
        self.BodyLabel_8 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.gridLayout.addWidget(self.BodyLabel_8, 3, 2, 2, 1)
        self.Fonts = LineEdit(parent=self.centralwidget)
        self.Fonts.setObjectName("Fonts")
        self.gridLayout.addWidget(self.Fonts, 9, 0, 1, 1)
        self.BodyLabel_5 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout.addWidget(self.BodyLabel_5, 10, 0, 1, 1)
        self.Speed = LineEdit(parent=self.centralwidget)
        self.Speed.setObjectName("Speed")
        self.gridLayout.addWidget(self.Speed, 3, 1, 2, 1)
        self.BodyLabel_3 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout.addWidget(self.BodyLabel_3, 2, 0, 1, 1)
        self.Github = PushButton(parent=self.centralwidget)
        self.Github.setStyleSheet("/* ==================== 基础按钮样式 ==================== */\n"
"/* 默认状态：青色背景，白色文字，保留圆角和边框 */\n"
"PushButton, ToolButton, ToggleButton, ToggleToolButton,\n"
"PrimaryPushButton, PrimaryToolButton {\n"
"    color: white;\n"
"    background-color: #4ca0af;\n"
"    border: 1px solid #45a049;\n"
"    border-bottom: 1px solid #007780;\n"
"    border-radius: 5px;\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* 悬停状态：背景保持青色，文字变为黑色 */\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover,\n"
"PrimaryPushButton:hover, PrimaryToolButton:hover {\n"
"    \n"
"    background-color: #45a049; /* 强制背景色不变 */\n"
"    border: 1px solid #45a049;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"/* 按下状态：背景保持青色，文字变为黑色（或深灰色以示反馈） */\n"
"PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed,\n"
"PrimaryPushButton:pressed, PrimaryToolButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.7); /* 按下时文字稍暗，提供视觉反馈 */\n"
"    background-color: #009faa; /* 强制背景色不变 */\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"/* 禁用状态：背景变灰，文字变灰 */\n"
"PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled,\n"
"PrimaryPushButton:disabled, PrimaryToolButton:disabled {\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"    border: 1px solid rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"/* ==================== 特殊按钮的内边距调整 ==================== */\n"
"ToolButton {\n"
"    padding: 5px 9px 6px 8px;\n"
"}\n"
"\n"
"PushButton[isPlaceholderText=true] {\n"
"    color: rgba(0, 0, 0, 0.6063);\n"
"}\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"DropDownToolButton, PrimaryDropDownToolButton {\n"
"    padding: 5px 31px 6px 8px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"/* ==================== 切换按钮的选中状态 ==================== */\n"
"/* 选中状态默认就是青色，所以文字保持白色 */\n"
"ToggleButton:checked,\n"
"ToggleToolButton:checked {\n"
"    color: white;\n"
"    background-color: #009faa;\n"
"    border: 1px solid #00a7b3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"/* 选中状态下悬停，文字变为黑色 */\n"
"ToggleButton:checked:hover,\n"
"ToggleToolButton:checked:hover {\n"
"    color: black;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"/* 选中状态下按下，文字变为深黑色 */\n"
"ToggleButton:checked:pressed,\n"
"ToggleToolButton:checked:pressed {\n"
"    color: rgba(0, 0, 0, 0.7);\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"/* 选中状态下禁用 */\n"
"ToggleButton:checked:disabled,\n"
"ToggleToolButton:checked:disabled {\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"    border: 1px solid rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"\n"
"/* ==================== 分割按钮 ==================== */\n"
"SplitDropButton,\n"
"PrimarySplitDropButton {\n"
"    border-left: none;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton,\n"
"#splitToolButton,\n"
"#primarySplitPushButton,\n"
"#primarySplitToolButton {\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton:pressed,\n"
"#splitToolButton:pressed,\n"
"SplitDropButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimarySplitDropButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"#primarySplitPushButton, #primarySplitToolButton {\n"
"    border-right: 1px solid #00a7b3;\n"
"}\n"
"\n"
"#primarySplitPushButton:pressed, #primarySplitToolButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"/* ==================== 其他控件（保留原始样式）==================== */\n"
"HyperlinkButton {\n"
"    padding: 6px 12px 6px 12px;\n"
"    color: #009faa;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=false] {\n"
"    padding: 6px 12px 6px 12px;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=true] {\n"
"    padding: 6px 12px 6px 36px;\n"
"}\n"
"\n"
"HyperlinkButton:hover {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:pressed {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.43);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"RadioButton {\n"
"    min-height: 24px;\n"
"    max-height: 24px;\n"
"    background-color: transparent;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    color: black;\n"
"}\n"
"\n"
"RadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 11px;\n"
"    border: 2px solid #999999;\n"
"    background-color: rgba(0, 0, 0, 5);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"RadioButton::indicator:hover {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"RadioButton::indicator:pressed {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(225, 224, 223),\n"
"            stop:1 rgb(225, 224, 223));\n"
"}\n"
"\n"
"RadioButton::indicator:checked {\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(255, 255, 255),\n"
"            stop:0.7 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"RadioButton::indicator:disabled {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"RadioButton::indicator:disabled:checked {\n"
"    border: none;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgba(0, 0, 0, 0.2169),\n"
"            stop:1 rgba(0, 0, 0, 0.2169));\n"
"}\n"
"\n"
"TransparentToolButton,\n"
"TransparentToggleToolButton,\n"
"TransparentDropDownToolButton,\n"
"TransparentPushButton,\n"
"TransparentDropDownPushButton,\n"
"TransparentTogglePushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"TransparentToolButton:hover,\n"
"TransparentToggleToolButton:hover,\n"
"TransparentDropDownToolButton:hover,\n"
"TransparentPushButton:hover,\n"
"TransparentDropDownPushButton:hover,\n"
"TransparentTogglePushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:pressed,\n"
"TransparentToggleToolButton:pressed,\n"
"TransparentDropDownToolButton:pressed,\n"
"TransparentPushButton:pressed,\n"
"TransparentDropDownPushButton:pressed,\n"
"TransparentTogglePushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:disabled,\n"
"TransparentToggleToolButton:disabled,\n"
"TransparentDropDownToolButton:disabled,\n"
"TransparentPushButton:disabled,\n"
"TransparentDropDownPushButton:disabled,\n"
"TransparentTogglePushButton:disabled {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"PillPushButton,\n"
"PillPushButton:hover,\n"
"PillPushButton:pressed,\n"
"PillPushButton:disabled,\n"
"PillPushButton:checked,\n"
"PillPushButton:checked:hover,\n"
"PillPushButton:checked:pressed,\n"
"PillPushButton:disabled:checked,\n"
"PillToolButton,\n"
"PillToolButton:hover,\n"
"PillToolButton:pressed,\n"
"PillToolButton:disabled,\n"
"PillToolButton:checked,\n"
"PillToolButton:checked:hover,\n"
"PillToolButton:checked:pressed,\n"
"PillToolButton:disabled:checked {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.Github.setObjectName("Github")
        self.gridLayout.addWidget(self.Github, 2, 3, 2, 1)
        self.BodyLabel_4 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout.addWidget(self.BodyLabel_4, 8, 0, 1, 1)
        self.Enable_music = CheckBox(parent=self.centralwidget)
        self.Enable_music.setObjectName("Enable_music")
        self.gridLayout.addWidget(self.Enable_music, 5, 0, 1, 1)
        self.BodyLabel_6 = BodyLabel(parent=self.centralwidget)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout.addWidget(self.BodyLabel_6, 6, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Color.addItem("green", userData="green")
        self.Color.addItem("red", userData="red")
        self.Color.addItem("blue", userData="blue ")
        self.Color.addItem("yellow", userData="yellow")
        self.Color.addItem("white", userData="white")
        self.Color.addItem("cyan", userData="cyan")
        self.Color.addItem("magenta", userData="magenta")
        self.Color.addItem("black", userData="black")

        items =["a","A","c","C","e","g","G","k","m","n","o","p","P","r","R","s","S"]
        self.Font_dict.addItems(items)
        self.music.addItem(text="佳豪小曲",userData="jiahao")
        self.music.addItem(text="Faded",userData="faded")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "柠檬小助手"))
        self.Color.setText(_translate("MainWindow", "请选择"))
        self.Font_dict.setText(_translate("MainWindow", "请选择"))
        self.BodyLabel_2.setText(_translate("MainWindow", "使用GPL3.0开源"))
        self.BodyLabel_7.setText(_translate("MainWindow", "代码速度"))
        self.BodyLabel.setText(_translate("MainWindow", "原项目UniMatrix"))
        self.music.setText(_translate("MainWindow", "音乐"))
        self.Run.setText(_translate("MainWindow", "启动！"))
        self.TitleLabel.setText(_translate("MainWindow", "欢迎使用柠檬小助手"))
        self.BodyLabel_8.setText(_translate("MainWindow", "%"))
        self.Fonts.setText(_translate("MainWindow", "请输入文本"))
        self.BodyLabel_5.setText(_translate("MainWindow", "代码雨预设字符集"))
        self.Speed.setText(_translate("MainWindow", "94"))
        self.BodyLabel_3.setText(_translate("MainWindow", "代码雨颜色"))
        self.Github.setText(_translate("MainWindow", "点我查看原项目主页"))
        self.BodyLabel_4.setText(_translate("MainWindow", "代码雨字符"))
        self.Enable_music.setText(_translate("MainWindow", "启用佳豪音乐？"))
        self.BodyLabel_6.setText(_translate("MainWindow", "TIP 不配置也能用"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, LineEdit, PushButton, TitleLabel
