# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create arm64 appimage

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
          libsdl2-2.0-0 \
          libsdl2-image-2.0-0 \
          libsdl2-mixer-2.0-0 \
          libsdl2-ttf-2.0-0 \
          libfreetype6 \
          libportmidi0 \
          libharfbuzz0b \
          libxcb-xinerama0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-render-util0 \
          libxcb-xkb1 \
          libxkbcommon-x11-0 \
          libgl1 \
          libegl1 \
          libdbus-1-3 \
          libssl3 \
          libsqlite3-0
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Download Appimage Python And Kit
      run: |
        wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-aarch64.AppImage
        wget https://github.com/niess/python-appimage/releases/download/python3.13/python3.13.8-cp313-cp313-manylinux2014_aarch64.AppImage
        chmod +x python3.13.8-cp313-cp313-manylinux2014_aarch64.AppImage
        chmod +x appimagetool-aarch64.AppImage
        ./python3.13.8-cp313-cp313-manylinux2014_aarch64.AppImage --appimage-extract
        ./squashfs-root/AppRun -m pip install -r requirements.txt
        ./appimagetool-aarch64.AppImage \
        --no-appstream \
        squashfs-root \
        python3.13_aarch64.AppImage
    - name: Create run script
      run: |
        echo -e '#!/bin/bash\nchmod +x python3.13_aarch64.AppImage\n./python3.14_aarch64.AppImage main.py' > run.sh
        chmod +x run.sh
        
    - name: Upload ARM64 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-appimage-arm64
        path: |
          python3.13_aarch64.AppImage
          run.sh
        retention-days: 7
